# HDL component dependency registry.
#
# Format:
# "<component_group>/<component>": [<dependency_group_1>, <dependency_group_2>, ...]
#
# <component_group> refers to the name of the directory containing the component.sv

'common/join2'             =[]
'common/register_slice'    =[]
'common/skid_buffer'       =['common']
'int/int_entrywise_product'=['common', 'int']
'int/int_multiply'         =[]
'matmul/simple_matmul'     =["int"]
