# HDL component dependency registry.
#
# Format:
# "<component_group>/<component>": [<dependency_group_1>, <dependency_group_2>, ...]
#
# <component_group> refers to the name of the directory containing the component.sv

'common/rtl/join2.sv'             =[]
'common/rtl/register_slice.sv'    =[]
'common/rtl/skid_buffer.sv'       =['common/rtl/register_slice.sv']
'int/rtl/int_adder_tree.sv'       =['int/rtl/int_adder_tree_layer.sv']
'int/rtl/int_adder_tree_layer.sv' =['common/rtl/register_slice.sv', 'int/rtl/int_adder_tree_node.sv']
'int/rtl/int_adder_tree_node.sv'  =['common/rtl/register_slice.sv']
'int/rtl/int_entrywise_product.sv'=['common/rtl/skid_buffer.sv', 'int/rtl/int_multiply.sv']
'int/rtl/int_multiply.sv'         =[]
'matmul/rtl/simple_matmul.sv'     =["int/rtl/int_entrywise_product.sv"]
