# HDL component dependency registry.
#
# Format:
# "<path_to_design.sv>": [<path_to_dependency_1>, <path_to_dependency_2>, ...]
# path is relative to hardware/user/components

"common/rtl/join2.sv"              = [  ]
"common/rtl/register_slice.sv"     = [  ]
"common/rtl/skid_buffer.sv"        = [ "common/rtl/register_slice.sv" ]
"int/rtl/int_adder_tree.sv"        = [ "int/rtl/int_adder_tree_layer.sv" ]
"int/rtl/int_adder_tree_layer.sv"  = [ "common/rtl/register_slice.sv", "int/rtl/int_adder_tree_node.sv" ]
"int/rtl/int_adder_tree_node.sv"   = [ "common/rtl/register_slice.sv" ]
"int/rtl/int_entrywise_product.sv" = [ "common/rtl/skid_buffer.sv", "int/rtl/int_multiply.sv" ]
"int/rtl/int_multiply.sv"          = [  ]
"matmul/rtl/simple_matmul.sv"      = [ "int/rtl/int_entrywise_product.sv" ]
